export const roundToNearestMillionOrBillion = (num: string) => {
  const number = parseInt(num);

  switch (true) {
    case Math.abs(number) >= 1e9:
      return Math.round((number / 1e9) * 10) / 10 + 'b';
    case Math.abs(number) >= 1e6:
      return Math.round((number / 1e6) * 10) / 10 + 'm';
    default:
      return number.toString();
  }
};

export const supportedCountries = [
  "Global",
  "United States",
  "Australia",
  "United Kingdom",
  "Canada",
  "India",
  "China",
  "Argentina",
  "Austria",
  "Bahrain",
  "Bangladesh",
  "Belgium",
  "Bermuda",
  "Botswana",
  "Brazil",
  "Bulgaria",
  "Chile",
  "Colombia",
  "Croatia",
  "Cyprus",
  "Czech Republic",
  "Denmark",
  "Egypt",
  "Estonia",
  "Finland",
  "France",
  "Germany",
  "Ghana",
  "Greece",
  "Hong Kong",
  "Hungary",
  "Iceland",
  "Indonesia",
  "Ireland",
  "Israel",
  "Italy",
  "Ivory Coast",
  "Jamaica",
  "Japan",
  "Jordan",
  "Kenya",
  "Kuwait",
  "Latvia",
  "Lithuania",
  "Luxembourg",
  "Malawi",
  "Malaysia",
  "Malta",
  "Mauritius",
  "Mexico",
  "Morocco",
  "Namibia",
  "Netherlands",
  "New Zealand",
  "Nigeria",
  "Norway",
  "Oman",
  "Pakistan",
  "Palestinian Authority",
  "Peru",
  "Philippines",
  "Poland",
  "Portugal",
  "Qatar",
  "Romania",
  "Russia",
  "Saudi Arabia",
  "Serbia",
  "Singapore",
  "Slovakia",
  "Slovenia",
  "South Africa",
  "South Korea",
  "Spain",
  "Sri Lanka",
  "Sweden",
  "Switzerland",
  "Taiwan",
  "Tanzania",
  "Thailand",
  "Trinidad & Tobago",
  "Tunisia",
  "Turkey",
  "Uganda",
  "Ukraine",
  "United Arab Emirates",
  "Venezuela",
  "Vietnam",
  "Zambia",
  "Zimbabwe"
];

